# Generated by Django 5.2.14 on 2026-07-27 12:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='التصنيف')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'التصنيفات',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='المنتج أو الخدمة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('unit', models.CharField(default='قطعة', max_length=50, verbose_name='الوحدة')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر الاسترشادي')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='marketplace.category')),
                ('supplier', models.ForeignKey(limit_choices_to={'role': 'supplier'}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='إجمالي العرض')),
                ('delivery_days', models.PositiveIntegerField(verbose_name='مدة التسليم بالأيام')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات العرض')),
                ('status', models.CharField(choices=[('pending', 'بانتظار المراجعة'), ('selected', 'تم الاختيار'), ('rejected', 'غير مختار'), ('withdrawn', 'مسحوب')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(limit_choices_to={'role': 'supplier'}, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عرض سعر',
                'verbose_name_plural': 'عروض الأسعار',
                'ordering': ['total_amount', 'delivery_days'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, unique=True)),
                ('agreed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('confirmed', 'مؤكد'), ('preparing', 'قيد التجهيز'), ('shipped', 'تم الشحن'), ('delivered', 'تم التسليم'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order', to='marketplace.quote')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='marketplace.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الطلب')),
                ('description', models.TextField(verbose_name='تفاصيل الاحتياج')),
                ('delivery_city', models.CharField(max_length=100, verbose_name='مدينة التسليم')),
                ('deadline', models.DateField(verbose_name='آخر موعد لاستقبال العروض')),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الميزانية من')),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الميزانية إلى')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('open', 'مفتوح للعروض'), ('evaluating', 'قيد المقارنة'), ('awarded', 'تم اختيار عرض'), ('closed', 'مغلق'), ('cancelled', 'ملغي')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to='marketplace.category')),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'طلب عرض سعر',
                'verbose_name_plural': 'طلبات عروض السعر',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='marketplace.rfq'),
        ),
        migrations.CreateModel(
            name='RFQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='البند')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='الكمية')),
                ('unit', models.CharField(default='قطعة', max_length=50, verbose_name='الوحدة')),
                ('specifications', models.CharField(blank=True, max_length=255, verbose_name='المواصفات')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.rfq')),
            ],
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('rfq', 'supplier'), name='one_quote_per_supplier'),
        ),
    ]
