# Generated by Django 5.2.14 on 2026-07-27 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_quote_delivery_days_alter_quote_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['total_amount', 'delivery_days'], 'verbose_name': 'Quote', 'verbose_name_plural': 'Quotes'},
        ),
        migrations.AlterModelOptions(
            name='rfq',
            options={'ordering': ['-created_at'], 'verbose_name': 'Request for quotation', 'verbose_name_plural': 'Requests for quotation'},
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Category name in English'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=180, verbose_name='Product or service'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Reference price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='قطعة', max_length=50, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='delivery_days',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Delivery time in days'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Quote notes'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('selected', 'Selected'), ('rejected', 'Not selected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Total quote'),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Maximum budget'),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Minimum budget'),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='deadline',
            field=models.DateField(verbose_name='Quote submission deadline'),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='delivery_city',
            field=models.CharField(max_length=100, verbose_name='Delivery city'),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='description',
            field=models.TextField(verbose_name='Requirements details'),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open for quotes'), ('evaluating', 'Under evaluation'), ('awarded', 'Quote awarded'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Request title'),
        ),
        migrations.AlterField(
            model_name='rfqitem',
            name='name',
            field=models.CharField(max_length=180, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='rfqitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='rfqitem',
            name='specifications',
            field=models.CharField(blank=True, max_length=255, verbose_name='Specifications'),
        ),
        migrations.AlterField(
            model_name='rfqitem',
            name='unit',
            field=models.CharField(default='قطعة', max_length=50, verbose_name='Unit'),
        ),
    ]
