# Generated by Django 5.2.14 on 2026-07-27 16:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_category_options_alter_quote_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('quote_received', 'Quote received'), ('quote_selected', 'Quote selected'), ('quote_rejected', 'Quote not selected'), ('order_status', 'Order status updated'), ('payment_submitted', 'Payment submitted'), ('payment_confirmed', 'Payment confirmed'), ('payment_rejected', 'Payment rejected'), ('review_received', 'Review received')], max_length=30, verbose_name='Notification type')),
                ('event_key', models.CharField(max_length=120, unique=True, verbose_name='Event key')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30, verbose_name='Previous status')),
                ('to_status', models.CharField(choices=[('awaiting_confirmation', 'Awaiting supplier confirmation'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=30, verbose_name='New status')),
                ('note', models.TextField(blank=True, verbose_name='Status note')),
                ('actor_role', models.CharField(blank=True, max_length=20, verbose_name='Actor role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order status event',
                'verbose_name_plural': 'Order status events',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('cash_on_delivery', 'Cash on delivery')], max_length=30, verbose_name='Payment method')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Payment amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Payment details submitted'), ('confirmed', 'Payment confirmed'), ('rejected', 'Payment rejected'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Payment status')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='Transfer reference')),
                ('note', models.TextField(blank=True, verbose_name='Payment note')),
                ('admin_note', models.TextField(blank=True, verbose_name='Administration note')),
                ('submission_count', models.PositiveIntegerField(default=0, verbose_name='Submission count')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Purchase order', 'verbose_name_plural': 'Purchase orders'},
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_days',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Agreed delivery time in days'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expected delivery date'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='rfq',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order', to='marketplace.rfq'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tracking_reference',
            field=models.CharField(blank=True, max_length=120, verbose_name='Tracking reference'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='agreed_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Agreed amount'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_number',
            field=models.CharField(max_length=30, unique=True, verbose_name='Order number'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('awaiting_confirmation', 'Awaiting supplier confirmation'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='awaiting_confirmation', max_length=30, verbose_name='Order status'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('agreed_amount__gt', 0)), name='purchase_order_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_days__gte', 1)), name='purchase_order_delivery_days_positive'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'selected')), fields=('rfq',), name='one_selected_quote_per_rfq'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_between_1_and_5'),
        ),
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='marketplace.purchaseorder'),
        ),
        migrations.AddField(
            model_name='notification',
            name='rfq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='marketplace.rfq'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderstatusevent',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderstatusevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='marketplace.purchaseorder'),
        ),
        migrations.AddField(
            model_name='payment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='marketplace.purchaseorder'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='marketplace_user_id_4c2c73_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
    ]
