# Generated by Django 5.2.14 on 2026-07-27 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_notification_orderstatusevent_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='marketplace.purchaseorder'),
        ),
    ]
