# Generated by Django 5.2.14 on 2026-07-27 16:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def snapshot_existing_order_items(apps, schema_editor):
    PurchaseOrder = apps.get_model("marketplace", "PurchaseOrder")
    PurchaseOrderItem = apps.get_model("marketplace", "PurchaseOrderItem")
    RFQItem = apps.get_model("marketplace", "RFQItem")
    Quote = apps.get_model("marketplace", "Quote")

    quote_to_rfq = dict(Quote.objects.values_list("pk", "rfq_id"))
    snapshots = []
    for order in PurchaseOrder.objects.all().iterator():
        rfq_id = order.rfq_id or quote_to_rfq.get(order.quote_id)
        if not rfq_id:
            continue
        for item in RFQItem.objects.filter(rfq_id=rfq_id).iterator():
            snapshots.append(
                PurchaseOrderItem(
                    order_id=order.pk,
                    name=item.name,
                    quantity=item.quantity,
                    unit=item.unit,
                    specifications=item.specifications,
                )
            )
    PurchaseOrderItem.objects.bulk_create(snapshots)


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_review_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Item')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantity')),
                ('unit', models.CharField(max_length=50, verbose_name='Unit')),
                ('specifications', models.CharField(blank=True, max_length=255, verbose_name='Specifications')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='marketplace.purchaseorder')),
            ],
            options={
                'verbose_name': 'Purchase order item',
                'verbose_name_plural': 'Purchase order items',
                'ordering': ['pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_order_item_quantity_positive')],
            },
        ),
        migrations.RunPython(
            snapshot_existing_order_items,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
