# Generated by Django 5.2.14 on 2026-07-27 18:08

import django.core.validators
from django.conf import settings
from django.db import migrations, models


def snapshot_notification_context(apps, schema_editor):
    Notification = apps.get_model("marketplace", "Notification")
    for notification in Notification.objects.select_related("rfq", "order").iterator():
        payload = {
            "request_title": notification.rfq.title if notification.rfq_id else "",
            "order_number": (
                notification.order.order_number if notification.order_id else ""
            ),
        }
        if notification.kind == "order_status":
            parts = notification.event_key.split(":")
            if len(parts) >= 4:
                payload["status"] = parts[2]
        notification.payload = payload
        update_fields = ["payload"]
        if notification.kind == "quote_rejected":
            notification.rfq_id = None
            notification.order_id = None
            update_fields.extend(["rfq", "order"])
        notification.save(update_fields=update_fields)


def deduplicate_supplier_product_names(apps, schema_editor):
    Product = apps.get_model("marketplace", "Product")
    seen = set()
    for product in Product.objects.order_by("supplier_id", "pk").iterator():
        key = (product.supplier_id, product.name)
        if key not in seen:
            seen.add(key)
            continue
        base_name = product.name
        attempt = 0
        while True:
            suffix = (
                f" ({product.pk})"
                if attempt == 0
                else f" ({product.pk}-{attempt})"
            )
            candidate = f"{base_name[: 180 - len(suffix)]}{suffix}"
            candidate_key = (product.supplier_id, candidate)
            if candidate_key not in seen:
                product.name = candidate
                product.save(update_fields=["name"])
                seen.add(candidate_key)
                break
            attempt += 1


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_purchaseorderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product or service', 'verbose_name_plural': 'Products and services'},
        ),
        migrations.AddField(
            model_name='notification',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Notification context'),
        ),
        migrations.RunPython(
            snapshot_notification_context,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_order_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Minimum order quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=80, verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Reference price'),
        ),
        migrations.RunPython(
            deduplicate_supplier_product_names,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('supplier', 'name'), name='unique_product_name_per_supplier'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_order_quantity__gt', 0)), name='product_minimum_quantity_positive'),
        ),
    ]
