# Generated by Django 5.2.14 on 2026-07-27 18:12

from django.db import migrations, models


def normalize_unit_codes(apps, schema_editor):
    mapping = {
        "قطعة": "piece",
        "piece": "piece",
        "مشروع": "project",
        "project": "project",
        "خدمة": "service",
        "service": "service",
        "كرتونة": "carton",
        "carton": "carton",
        "كيلوغرام": "kilogram",
        "kilogram": "kilogram",
    }
    for model_name in ("Product", "PurchaseOrderItem", "RFQItem"):
        Model = apps.get_model("marketplace", model_name)
        for old_value, code in mapping.items():
            Model.objects.filter(unit=old_value).update(unit=code)


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_product_options_notification_payload_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_unit_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('project', 'Project'), ('service', 'Service'), ('carton', 'Carton'), ('kilogram', 'Kilogram')], default='piece', max_length=50, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('project', 'Project'), ('service', 'Service'), ('carton', 'Carton'), ('kilogram', 'Kilogram')], max_length=50, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='rfqitem',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('project', 'Project'), ('service', 'Service'), ('carton', 'Carton'), ('kilogram', 'Kilogram')], default='piece', max_length=50, verbose_name='Unit'),
        ),
    ]
