# Generated by Django 5.2.14 on 2026-07-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='business_type',
            field=models.CharField(blank=True, max_length=120, verbose_name='Business type'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='description',
            field=models.TextField(blank=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Commercial registration number'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='trade_name',
            field=models.CharField(max_length=180, verbose_name='Organization name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Project owner'), ('supplier', 'Supplier'), ('staff', 'Platform administration')], default='owner', max_length=20, verbose_name='Role'),
        ),
    ]
