# Generated by Django 5.2.14 on 2026-07-27 18:08

import accounts.models
import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


def normalize_unique_emails(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    seen = set()
    for user in User.objects.order_by("date_joined", "pk").iterator():
        normalized = (user.email or "").strip().lower()
        if not normalized:
            continue
        if normalized in seen:
            user.email = ""
        else:
            user.email = normalized
            seen.add(normalized)
        user.save(update_fields=["email"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_companyprofile_business_type_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='registration_document',
            field=models.FileField(blank=True, upload_to=accounts.models.company_document_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Registration document'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(normalize_unique_emails, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email', ''), _negated=True), name='unique_user_email_case_insensitive'),
        ),
    ]
